version: '3.8'

services:
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:80"
  #   restart: always

  db:
    image: postgres:15
    container_name: db-store-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  app:
    build:
      context: backend
      dockerfile: ./Dockerfile
    container_name: app-store-1
    environment:
      JWT_SECRET: 8f3a9b2c7d4e1f6a5b8c9d0e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2
      JWT_ACCESS_TOKEN_TIME: 15
      JWT_REFRESH_TOKEN_TIME: 7
      JWT_ALGORITHM: HS256
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173
      ASSEMBLYAI_API_KEY: b526d483f1b543778c65450cf60d1379
      DEBUG: false
      APPLICATION_PORT: 8000
      SCIBOX_API_KEY: sk-9KZTGbeiILvRQ5g_Jc2lRQ
      SCIBOX_BASE_URL: https://llm.t1v.scibox.tech/v1
      ML_API_URL: http://ml-service:8080
      JUDGE0_API_URL: http://judge0-server:2358
    depends_on:
      db: 
        condition: service_healthy
      ml-service:
        condition: service_started
      judge0-server:
        condition: service_started
    networks:
      - app-network
    ports:
      - "8000:8000"
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8000"

  ml-service:
    build:
      context: ML
      dockerfile: Dockerfile
    container_name: ml-service
    environment:
      SCIBOX_API_KEY: sk-9KZTGbeiILvRQ5g_Jc2lRQ
      SCIBOX_BASE_URL: https://llm.t1v.scibox.tech/v1
    ports:
      - "8080:8080"
    networks:
      - app-network

  judge0-server:
    image: judge0/judge0:1.13.1
    container_name: judge0-server
    restart: always
    privileged: true
    ports:
      - "2358:2358"
    environment:
      - AUTH_DISABLE_USERNAME_AND_PASSWORD=true
      - JUDGE0_WORKERS=1
      - REDIS_HOST=judge0-redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://judge0-redis:6379
      - POSTGRES_HOST=judge0-db
      - POSTGRES_PORT=5432
      - POSTGRES_URL=postgresql://judge0:judge0@judge0-db:5432/judge0
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
    depends_on:
      judge0-db:
        condition: service_healthy
      judge0-redis:
        condition: service_started
    networks:
      - app-network

  judge0-workers:
    image: judge0/judge0:1.13.1
    container_name: judge0-workers
    restart: always
    command: ["./scripts/workers"]
    environment:
      - AUTH_DISABLE_USERNAME_AND_PASSWORD=true
      - REDIS_HOST=judge0-redis
      - REDIS_PORT=6379
      - REDIS_URL=redis://judge0-redis:6379
      - POSTGRES_HOST=judge0-db
      - POSTGRES_PORT=5432
      - POSTGRES_URL=postgresql://judge0:judge0@judge0-db:5432/judge0
      - POSTGRES_DB=judge0
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
    depends_on:
      - judge0-db
      - judge0-redis
    networks:
      - app-network
    privileged: true

  judge0-db:
    image: postgres:13
    container_name: judge0-db
    restart: always
    environment:
      - POSTGRES_USER=judge0
      - POSTGRES_PASSWORD=judge0
      - POSTGRES_DB=judge0
    volumes:
      - judge0-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U judge0"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  judge0-redis:
    image: redis:6.0
    container_name: judge0-redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - judge0-redis-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  judge0-postgres-data:
  judge0-redis-data:
