"""add creator_id to interview

Revision ID: e5dc874670fd
Revises: 
Create Date: 2025-11-26 00:51:19.054236

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5dc874670fd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codetask',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('initial_code', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('test_cases', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('interview',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('job_role_description', sa.Text(), nullable=False),
    sa.Column('amount_of_tasks', sa.Integer(), nullable=False),
    sa.Column('key_skills', sa.JSON(), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='interviewstatus'), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('public_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_creator_id'), 'interview', ['creator_id'], unique=False)
    op.create_index(op.f('ix_interview_public_token'), 'interview', ['public_token'], unique=True)
    op.create_index(op.f('ix_interview_user_id'), 'interview', ['user_id'], unique=False)
    op.create_table('chatmessage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.Enum('USER', 'AI', name='messagesender'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatmessage_interview_id'), 'chatmessage', ['interview_id'], unique=False)
    op.create_table('interviewstep',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DIALOG', 'CODE_TASK', name='interviewsteptype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='interviewstepstatus'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('code_task_id', sa.UUID(), nullable=True),
    sa.Column('user_code', sa.Text(), nullable=True),
    sa.Column('code_feedback', sa.Text(), nullable=True),
    sa.Column('code_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code_task_id'], ['codetask.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviewstep_interview_id'), 'interviewstep', ['interview_id'], unique=False)
    op.create_table('codetestresult',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('interview_step_id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PASSED', 'FAILED', 'ERROR', name='codetestresultstatus'), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_step_id'], ['interviewstep.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codetestresult_interview_step_id'), 'codetestresult', ['interview_step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codetestresult_interview_step_id'), table_name='codetestresult')
    op.drop_table('codetestresult')
    op.drop_index(op.f('ix_interviewstep_interview_id'), table_name='interviewstep')
    op.drop_table('interviewstep')
    op.drop_index(op.f('ix_chatmessage_interview_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_interview_user_id'), table_name='interview')
    op.drop_index(op.f('ix_interview_public_token'), table_name='interview')
    op.drop_index(op.f('ix_interview_creator_id'), table_name='interview')
    op.drop_table('interview')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('codetask')
    # ### end Alembic commands ###

